version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Use the CircleCI Node.js image
    steps:
      - checkout  # Pull the code from your GitHub repository
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
